//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef", IsNullable = false)]
public partial class WITD2
{

    private WITDWORKITEMTYPE wORKITEMTYPEField;

    private string[] textField;

    private string applicationField;

    private decimal versionField;

    /// <remarks/>
    public WITDWORKITEMTYPE WORKITEMTYPE
    {
        get
        {
            return this.wORKITEMTYPEField;
        }
        set
        {
            this.wORKITEMTYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string application
    {
        get
        {
            return this.applicationField;
        }
        set
        {
            this.applicationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPE
{

    private string dESCRIPTIONField;

    private WITDWORKITEMTYPEGLOBALLISTS gLOBALLISTSField;

    private WITDWORKITEMTYPEFIELDS fIELDSField;

    private WITDWORKITEMTYPEWORKFLOW wORKFLOWField;

    private WITDWORKITEMTYPEFORM fORMField;

    private string[] textField;

    private string nameField;

    /// <remarks/>
    public string DESCRIPTION
    {
        get
        {
            return this.dESCRIPTIONField;
        }
        set
        {
            this.dESCRIPTIONField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEGLOBALLISTS GLOBALLISTS
    {
        get
        {
            return this.gLOBALLISTSField;
        }
        set
        {
            this.gLOBALLISTSField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEFIELDS FIELDS
    {
        get
        {
            return this.fIELDSField;
        }
        set
        {
            this.fIELDSField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOW WORKFLOW
    {
        get
        {
            return this.wORKFLOWField;
        }
        set
        {
            this.wORKFLOWField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEFORM FORM
    {
        get
        {
            return this.fORMField;
        }
        set
        {
            this.fORMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEGLOBALLISTS
{

    private WITDWORKITEMTYPEGLOBALLISTSGLOBALLIST[] gLOBALLISTField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GLOBALLIST")]
    public WITDWORKITEMTYPEGLOBALLISTSGLOBALLIST[] GLOBALLIST
    {
        get
        {
            return this.gLOBALLISTField;
        }
        set
        {
            this.gLOBALLISTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEGLOBALLISTSGLOBALLIST
{

    private WITDWORKITEMTYPEGLOBALLISTSGLOBALLISTLISTITEM[] lISTITEMField;

    private string[] textField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LISTITEM")]
    public WITDWORKITEMTYPEGLOBALLISTSGLOBALLISTLISTITEM[] LISTITEM
    {
        get
        {
            return this.lISTITEMField;
        }
        set
        {
            this.lISTITEMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEGLOBALLISTSGLOBALLISTLISTITEM
{

    private string valueField;

    private string valueField1;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField1;
        }
        set
        {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFIELDS
{

    private WITDWORKITEMTYPEFIELDSFIELD[] fIELDField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FIELD")]
    public WITDWORKITEMTYPEFIELDSFIELD[] FIELD
    {
        get
        {
            return this.fIELDField;
        }
        set
        {
            this.fIELDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFIELDSFIELD
{

    private string hELPTEXTField;

    private string[] textField;

    private string nameField;

    private string refnameField;

    private string typeField;

    private string reportableField;

    /// <remarks/>
    public string HELPTEXT
    {
        get
        {
            return this.hELPTEXTField;
        }
        set
        {
            this.hELPTEXTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string refname
    {
        get
        {
            return this.refnameField;
        }
        set
        {
            this.refnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string reportable
    {
        get
        {
            return this.reportableField;
        }
        set
        {
            this.reportableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOW
{

    private WITDWORKITEMTYPEWORKFLOWSTATES sTATESField;

    private WITDWORKITEMTYPEWORKFLOWTRANSITIONS tRANSITIONSField;

    private string[] textField;

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOWSTATES STATES
    {
        get
        {
            return this.sTATESField;
        }
        set
        {
            this.sTATESField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOWTRANSITIONS TRANSITIONS
    {
        get
        {
            return this.tRANSITIONSField;
        }
        set
        {
            this.tRANSITIONSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWSTATES
{

    private WITDWORKITEMTYPEWORKFLOWSTATESSTATE[] sTATEField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STATE")]
    public WITDWORKITEMTYPEWORKFLOWSTATESSTATE[] STATE
    {
        get
        {
            return this.sTATEField;
        }
        set
        {
            this.sTATEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWSTATESSTATE
{

    private WITDWORKITEMTYPEWORKFLOWSTATESSTATEFIELDS fIELDSField;

    private string[] textField;

    private string valueField;

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOWSTATESSTATEFIELDS FIELDS
    {
        get
        {
            return this.fIELDSField;
        }
        set
        {
            this.fIELDSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWSTATESSTATEFIELDS
{

    private WITDWORKITEMTYPEWORKFLOWSTATESSTATEFIELDSFIELD[] fIELDField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FIELD")]
    public WITDWORKITEMTYPEWORKFLOWSTATESSTATEFIELDSFIELD[] FIELD
    {
        get
        {
            return this.fIELDField;
        }
        set
        {
            this.fIELDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWSTATESSTATEFIELDSFIELD
{

    private string eMPTYField;

    private string[] textField;

    private string refnameField;

    /// <remarks/>
    public string EMPTY
    {
        get
        {
            return this.eMPTYField;
        }
        set
        {
            this.eMPTYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string refname
    {
        get
        {
            return this.refnameField;
        }
        set
        {
            this.refnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWTRANSITIONS
{

    private WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITION[] tRANSITIONField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TRANSITION")]
    public WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITION[] TRANSITION
    {
        get
        {
            return this.tRANSITIONField;
        }
        set
        {
            this.tRANSITIONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITION
{

    private WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONREASONS rEASONSField;

    private WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONFIELDS fIELDSField;

    private WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONACTIONS aCTIONSField;

    private string[] textField;

    private string fromField;

    private string toField;

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONREASONS REASONS
    {
        get
        {
            return this.rEASONSField;
        }
        set
        {
            this.rEASONSField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONFIELDS FIELDS
    {
        get
        {
            return this.fIELDSField;
        }
        set
        {
            this.fIELDSField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONACTIONS ACTIONS
    {
        get
        {
            return this.aCTIONSField;
        }
        set
        {
            this.aCTIONSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string from
    {
        get
        {
            return this.fromField;
        }
        set
        {
            this.fromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string to
    {
        get
        {
            return this.toField;
        }
        set
        {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONREASONS
{

    private WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONREASONSDEFAULTREASON dEFAULTREASONField;

    private string[] textField;

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONREASONSDEFAULTREASON DEFAULTREASON
    {
        get
        {
            return this.dEFAULTREASONField;
        }
        set
        {
            this.dEFAULTREASONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONREASONSDEFAULTREASON
{

    private string valueField;

    private string valueField1;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField1;
        }
        set
        {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONFIELDS
{

    private WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONFIELDSFIELD[] fIELDField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FIELD")]
    public WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONFIELDSFIELD[] FIELD
    {
        get
        {
            return this.fIELDField;
        }
        set
        {
            this.fIELDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONFIELDSFIELD
{

    private string rEADONLYField;

    private string[] textField;

    private string refnameField;

    /// <remarks/>
    public string READONLY
    {
        get
        {
            return this.rEADONLYField;
        }
        set
        {
            this.rEADONLYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string refname
    {
        get
        {
            return this.refnameField;
        }
        set
        {
            this.refnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONACTIONS
{

    private WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONACTIONSACTION aCTIONField;

    private string[] textField;

    /// <remarks/>
    public WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONACTIONSACTION ACTION
    {
        get
        {
            return this.aCTIONField;
        }
        set
        {
            this.aCTIONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEWORKFLOWTRANSITIONSTRANSITIONACTIONSACTION
{

    private string valueField;

    private string valueField1;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField1;
        }
        set
        {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORM
{

    private WITDWORKITEMTYPEFORMLayout layoutField;

    private WITDWORKITEMTYPEFORMWebLayout webLayoutField;

    private string[] textField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMLayout Layout
    {
        get
        {
            return this.layoutField;
        }
        set
        {
            this.layoutField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEFORMWebLayout WebLayout
    {
        get
        {
            return this.webLayoutField;
        }
        set
        {
            this.webLayoutField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayout
{

    private WITDWORKITEMTYPEFORMLayoutGroup[] groupField;

    private WITDWORKITEMTYPEFORMLayoutTabGroup tabGroupField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Group")]
    public WITDWORKITEMTYPEFORMLayoutGroup[] Group
    {
        get
        {
            return this.groupField;
        }
        set
        {
            this.groupField = value;
        }
    }

    /// <remarks/>
    public WITDWORKITEMTYPEFORMLayoutTabGroup TabGroup
    {
        get
        {
            return this.tabGroupField;
        }
        set
        {
            this.tabGroupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutGroup
{

    private WITDWORKITEMTYPEFORMLayoutGroupColumn columnField;

    private string[] textField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMLayoutGroupColumn Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutGroupColumn
{

    private WITDWORKITEMTYPEFORMLayoutGroupColumnControl controlField;

    private string[] textField;

    private int percentWidthField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMLayoutGroupColumnControl Control
    {
        get
        {
            return this.controlField;
        }
        set
        {
            this.controlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PercentWidth
    {
        get
        {
            return this.percentWidthField;
        }
        set
        {
            this.percentWidthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutGroupColumnControl
{

    private string fieldNameField;

    private string typeField;

    private string labelField;

    private string labelPositionField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string FieldName
    {
        get
        {
            return this.fieldNameField;
        }
        set
        {
            this.fieldNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string LabelPosition
    {
        get
        {
            return this.labelPositionField;
        }
        set
        {
            this.labelPositionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutTabGroup
{

    private WITDWORKITEMTYPEFORMLayoutTabGroupTab[] tabField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tab")]
    public WITDWORKITEMTYPEFORMLayoutTabGroupTab[] Tab
    {
        get
        {
            return this.tabField;
        }
        set
        {
            this.tabField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutTabGroupTab
{

    private WITDWORKITEMTYPEFORMLayoutTabGroupTabGroup groupField;

    private string[] textField;

    private string labelField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMLayoutTabGroupTabGroup Group
    {
        get
        {
            return this.groupField;
        }
        set
        {
            this.groupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutTabGroupTabGroup
{

    private WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumn columnField;

    private string[] textField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumn Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumn
{

    private WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroup[] groupField;

    private string[] textField;

    private int percentWidthField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Group")]
    public WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroup[] Group
    {
        get
        {
            return this.groupField;
        }
        set
        {
            this.groupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PercentWidth
    {
        get
        {
            return this.percentWidthField;
        }
        set
        {
            this.percentWidthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroup
{

    private WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroupColumn[] columnField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Column")]
    public WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroupColumn[] Column
    {
        get
        {
            return this.columnField;
        }
        set
        {
            this.columnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroupColumn
{

    private WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroupColumnControl controlField;

    private string[] textField;

    private int percentWidthField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroupColumnControl Control
    {
        get
        {
            return this.controlField;
        }
        set
        {
            this.controlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PercentWidth
    {
        get
        {
            return this.percentWidthField;
        }
        set
        {
            this.percentWidthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMLayoutTabGroupTabGroupColumnGroupColumnControl
{

    private string fieldNameField;

    private string typeField;

    private string labelField;

    private string labelPositionField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string FieldName
    {
        get
        {
            return this.fieldNameField;
        }
        set
        {
            this.fieldNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string LabelPosition
    {
        get
        {
            return this.labelPositionField;
        }
        set
        {
            this.labelPositionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMWebLayout
{

    private WITDWORKITEMTYPEFORMWebLayoutSystemControls systemControlsField;

    private WITDWORKITEMTYPEFORMWebLayoutPage[] pageField;

    private string[] textField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMWebLayoutSystemControls SystemControls
    {
        get
        {
            return this.systemControlsField;
        }
        set
        {
            this.systemControlsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Page")]
    public WITDWORKITEMTYPEFORMWebLayoutPage[] Page
    {
        get
        {
            return this.pageField;
        }
        set
        {
            this.pageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMWebLayoutSystemControls
{

    private WITDWORKITEMTYPEFORMWebLayoutSystemControlsControl[] controlField;

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Control")]
    public WITDWORKITEMTYPEFORMWebLayoutSystemControlsControl[] Control
    {
        get
        {
            return this.controlField;
        }
        set
        {
            this.controlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMWebLayoutSystemControlsControl
{

    private string labelField;

    private string typeField;

    private string fieldNameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string FieldName
    {
        get
        {
            return this.fieldNameField;
        }
        set
        {
            this.fieldNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMWebLayoutPage
{

    private WITDWORKITEMTYPEFORMWebLayoutPageSection[] sectionField;

    private string[] textField;

    private string labelField;

    private string layoutModeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Section")]
    public WITDWORKITEMTYPEFORMWebLayoutPageSection[] Section
    {
        get
        {
            return this.sectionField;
        }
        set
        {
            this.sectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string LayoutMode
    {
        get
        {
            return this.layoutModeField;
        }
        set
        {
            this.layoutModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMWebLayoutPageSection
{

    private WITDWORKITEMTYPEFORMWebLayoutPageSectionGroup groupField;

    private string[] textField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMWebLayoutPageSectionGroup Group
    {
        get
        {
            return this.groupField;
        }
        set
        {
            this.groupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMWebLayoutPageSectionGroup
{

    private WITDWORKITEMTYPEFORMWebLayoutPageSectionGroupControl controlField;

    private string[] textField;

    private string labelField;

    /// <remarks/>
    public WITDWORKITEMTYPEFORMWebLayoutPageSectionGroupControl Control
    {
        get
        {
            return this.controlField;
        }
        set
        {
            this.controlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string Label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef")]
public partial class WITDWORKITEMTYPEFORMWebLayoutPageSectionGroupControl
{

    private string labelField;

    private string typeField;

    private string fieldNameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string Label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string FieldName
    {
        get
        {
            return this.fieldNameField;
        }
        set
        {
            this.fieldNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}
